2019-07-08 19:10:53,575 ERROR: Exception on /explore [GET] [in /home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lomolo/Projects/microblog/app/routes.py", line 124, in explore
    return render_template('index.html', title='Explore', posts=posts)
NameError: global name 'posts' is not defined
2019-07-08 19:11:53,679 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 19:28:17,097 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 19:49:38,231 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 19:49:54,270 ERROR: Exception on /index [GET] [in /home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lomolo/Projects/microblog/app/routes.py", line 37, in index
    next_url=url_for('index', page=post.next_num) if posts.has_next else None
UnboundLocalError: local variable 'post' referenced before assignment
2019-07-08 19:50:59,753 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 19:59:11,538 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 20:01:56,971 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
